// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mscrwrcrkgxyckgbmyzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zY3J3cmNya2d4eWNrZ2JteXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTg4NjksImV4cCI6MjA2MDE5NDg2OX0.fu4iIh9dRUphU8rBQ3LDk8qKe7mTSv7ZSaqLv8lhEkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);